# Generated by Django 5.1.15 on 2026-07-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_create_users',
            field=models.BooleanField(default=False),
        ),
    ]
