# Generated by Django 5.1.15 on 2026-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_can_create_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='manager_notes',
            field=models.TextField(blank=True),
        ),
    ]
