# Generated by Django 5.1.15 on 2026-07-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leaverequest_manager_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_manage_all_records',
            field=models.BooleanField(default=False),
        ),
    ]
